server:
  port: 8004

spring:
  application:
    name: api-order

eureka:
  instance:
    hostname: eureka7001.com
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

logging:
  level:
    root: info
